### ISSUE TITLE
Blur lost on iOS 10

### ISSUE THREAD

**Issue by alexandre-g** [devedbox/AXPopoverView#4]
![image-icm4xwcxtm](https://cloud.githubusercontent.com/assets/9635561/18900153/6098b6ba-8582-11e6-87e2-7ef075359153.png)
Still ok on 9.3

**Comment by devedbox** [comment]
This may be a bug of the ios 10.0. Effect view won't work if setting a mask layer to the effect view on 10.0 but normal blow 10.0.

**Comment by devedbox** [comment]
@alexandre-g This may be a bug of the ios 10.0. Effect view won't work if setting a mask layer to the effect view on 10.0 but normal blow 10.0.
