### ISSUE TITLE
It's awesome, but can't customize contentView

### ISSUE THREAD

**Issue by aelam** [devedbox/AXPopoverView#5]
I think the header, footer, progress, title, detail are redundant.
It can be used only by you.
what others want is set a contentView

**Comment by devedbox** [comment]
Sorry for the API perplexity. You can set `headerMode` to `AXPopoverCustomView` and then set your `contentView` to `headerView`. This is how the custom content view  works.

**Comment by aelam** [comment]
Strongly recommend to separate the configurable contentView to a subspec and current contentView, progress view or whatever to a higher subspec 



发自我的 iPhone

**Comment by devedbox** [comment]
Thanks, I'll think about it.
